name: "Build cinewrax app docker image"

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tag:
    name: Extract short sha
    runs-on: ubuntu-latest
    outputs:
      short: ${{ fromJSON(steps.sha.outputs.result) }}
    steps:
      - name: Extract short SHA
        id: sha
        uses: actions/github-script@v7.0.1
        with:
          script: return context.sha.substring(0, 7);

  build-app:
    needs: [ tag ]
    runs-on: ubuntu-latest
    name: Build Cinewrax App
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: apps/cinewrax/Dockerfile
          context: ./apps
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          push: true
          tags: pldin601/cinewrax-apps-cinewrax:${{ needs.tag.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
