name: "Build pubsub app docker image"

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tag:
    name: Extract tag name
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ fromJSON(steps.tag.outputs.result) }}
    steps:
      - name: Extract the tag name
        id: tag
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref === "refs/heads/main"
              ? 'latest'
              : context.payload.ref.replace(/^refs\/(tags|heads)\//, '');

  build-app:
    needs: [ tag ]
    runs-on: ubuntu-latest
    name: Build Pubsub App
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: apps/pubsub/Dockerfile
          context: ./apps
          push: true
          tags: pldin601/cinewrax-apps-pubsub:${{ needs.tag.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
